# Generated by Django 4.2.8 on 2024-01-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_desig', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
